replicaCount: 2

image:
  repository: atmaram/fff-product
  tag: latest
  pullPolicy: Always

targetEnv:
  name: Prod

service:
  name: product
  port: 8080
  targetPort: 8080
  nodePort: 30301

resources:
  limits:
    cpu: 30m
    memory: 300Mi
  requests:
    cpu: 10m
    memory: 128Mi